name: 'Workflow of Child REPO'

on:
  repository_dispatch:
  push:
    branches:
      - main

jobs: 
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main
      - name: Echo Workflow name
        shell: bash
        run: |
          echo "I am Workflow of Child REPO"
          sleep 60s